---
title: "p8105_hw5_wq2161"
author: "Wanxin Qi"
date: "11/14/2021"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Problem 1


## Problem 2

Create a tidy dataframe containing data from all participants, including the subject ID, arm, and observations over time. Make a spaghetti plot showing observations on each subject over time, and comment on differences between groups.

```{r long_study, message = FALSE}
empty_df = 
  tibble(
    file_name = list.files("data", full.names = TRUE)
  )

read_df = function(path) {
  file_data = read_csv(path)
}

long_study = 
  empty_df %>%
  mutate(
    data_value = purrr::map(pull(empty_df, file_name), read_df),
    file_name = substr(file_name, 6, 11)
  ) %>%
  unnest(cols = data_value)

long_study =
  long_study %>%
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    values_to = "data_value"
  ) %>%
  mutate(
    week = substr(week, 6, 6),
    week = as.integer(week)
  )

long_study

long_study %>%
  ggplot(aes(x = week, y = data_value)) +
  geom_line(aes(color = file_name), alpha = .5) +
  labs(
    title = "Observations On Each Subject Over Time",
    x = "Week",
    y = "Data"
  )
```


## Problem 3